### Obtener facturas por usuario
GET http://localhost:3000/invoices/1?page=1&limit=10
Content-Type: application/json

### Crear una nueva factura
POST http://localhost:3000/invoices
Content-Type: application/json

{
  "invoiceNumber": "INV-001",
  "path": "/invoices/inv001.pdf",
  "issueDate": "2024-08-30",
  "dueDate": "2024-09-15",
  "amount": 1500.00,
  "userId": 1,
  "invoiceStatusId": 2,
  "companyId": 1
}

### Actualizar una nueva factura
PUT http://localhost:3000/invoices/1
Content-Type: application/json

{
  "invoiceNumber": "INV-001",
  "path": "/invoices/inv001.pdf",
  "issueDate": "2024-08-30",
  "dueDate": "2024-09-15",
  "amount": 1500.00,
  "userId": 1,
  "invoiceStatusId": 2,
  "companyId": 1
}

### Obtener facturas por id
GET http://localhost:3000/invoices/getbyid/1
Content-Type: application/json
###
GET http://localhost:3000/invoices/check-invoice-number?invoiceNumber=INV-001
