
# ========== JOSE ==========
### Obtener facturas por id
GET http://localhost:3000/invoices/user/11
Content-Type: application/json

### Obtener facturas por id
GET http://localhost:3000/invoices/permision/1
Content-Type: application/json

### (JOSE)
GET http://localhost:3000/vouchers/1

### (JOSE)
GET http://localhost:3000/invoices/user/11

###   
PUT http://localhost:3000/invoices/permision/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksInN1YiI6MTksImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsImlzQWRtaW4iOnRydWUsIm5hbWVzIjoiVXNlciIsImxhc3ROYW1lIjoiRXhhbXBsZSIsImlhdCI6MTcyNjY5MDQ4NywiZXhwIjoxNzI2Nzc2ODg3fQ.hFB-PXCxLe7rkfBSgq4a_PU-H7o3169Kbxv06YUDMIU

[
    {
        "userId": 11,
        "permissionTypeId":2
    },
    {
        "userId": 12,
        "permissionTypeId":1
    }
]