# ========== Auth ==========
### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "userasdf@example.com",
  "password": "password123",
  "Names": "John",
  "LastName": "Doe",
  "Position": "Manager"
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

# ========== Users ==========
### get user by ID
GET http://localhost:3000/users/7b509208-ac10-494c-a82a-721a6717dc9d


# ========== Users ==========
### update user
PUT http://localhost:3000/users/5007bb61-61b8-444e-92ab-9db36dff62cb
Content-Type: application/json

{
  "email": "newemail@example.com",
  "Names": "John Updated",
  "LastName": "Doe Updated",
  "Position": "Manager",
  "mfaEnabled": false,
  "active": true
}

### delete user
DELETE http://localhost:3000/users/7b509208-ac10-494c-a82a-721a6717dc9d



# ========== Users ==========
### verify email
PUT http://localhost:3000/users/verify-email/newemail@example.com



# ========== Users ==========
### get paginated users
GET http://localhost:3000/users?page=1&limit=5

### get all users
GET http://localhost:3000/users
