### Send an email
POST http://localhost:3000/email/send
Content-Type: application/json

{
  "to": "fgp555@gmail.com",
  "subject": "Test Email",
  "text": "This is a test email sent from NestJS!"
}

### Password Reset
POST http://localhost:3000/auth/reset-password?token=ZmdwNTU1QGdtYWlsLmNvbQ==
Content-Type: application/json

{
  "newPassword": "newsecurepassword"
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "fgp555@gmail.com",
  "password": "newsecurepassword"
}


### get paginated users
GET http://localhost:3000/users?page=1&limit=2

### get all users
GET http://localhost:3000/users

### get user by ID
GET http://localhost:3000/users/1

### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "fgp555@gmail.com",
  "password": "password123",
  "Names": "John",
  "LastName": "Doe",
  "Position": "Manager"
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

### update user
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "email": "newemail@example.com",
  "Names": "John Updated",
  "LastName": "Doe Updated",
  "Position": "Manager",
  "mfaEnabled": false,
  "active": true
}

### delete user
DELETE http://localhost:3000/users/1


